name: Create Tag

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: '0'

    - id: auto-tag
      name: Github Tag Bump
      uses: anothrNick/github-tag-action@1.67.0
      with:
        GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
        WITH_V: true
        RELEASE_BRANCHES: main
        DEFAULT_BUMP: patch
        INITIAL_VERSION: "0.1.0"

    - id: extract-version-numbers
      name: "Extract Version Numbers"
      run: |
        tag="${{ steps.auto-tag.outputs.net_tag }}"
        version=${tag#v}
        major="$(echo $version | cut -d. -f1)"
        minor="$(echo $version | cut -d. -f2)"
        revision="$(echo $version | cut -d. -f3)"
        message="$(git log --format=%B -n 1)"
        echo "::set-output name=major::$major"
        echo "::set-output name=minor::$minor"
        echo "::set-output name=revision::$revision"
        echo "::set-output name=message::$message"

    - uses: rickstaa/action-create-tag@v1
      name: "Create Full Version Tag"
      with:
        tagname: "v${{ steps.extract-version-numbers.outputs.major }}.${{ steps.extract-version-numbers.outputs.minor }}.${{ steps.extract-version-numbers.outputs.revision }}"

    - name: "Tag Major Version"
      uses: rickstaa/action-create-tag@v1
      with:
        tagname: "v${{ steps.extract-version-numbers.outputs.major }}"

    - name: Check Commit Message
      id: check-commit-message
      shell: bash
      run: |
        commit_msg="$(git log --no-merges -1 --pretty=format:"%s%n%n%b")"
        echo "::group::Commit Message"
        echo "${commit_msg}"
        if echo "${commit_msg}" | grep "#norelease" --ignore-case > /dev/null
        then
          echo '::set-output name=is-release::false'
          echo "Commit message contains '#norelease'"
        else
          echo '::set-output name=is-release::true'
          echo "Commit message does NOT contain '#norelease'"
        fi

    - name: Create GitHub Release
      uses: ncipollo/release-action@v1
      if: ${{ steps.check-commit-message.outputs.is-release == 'true' }}
      with:
        tag: ${{ steps.auto-tag.outputs.net_tag }}
        bodyFile: "RELEASE_NOTES.md"
        token: ${{ secrets.GITHUB_TOKEN }}
